version: '2'

services:
  postgres:
    build: 
      context : .
      args:
        proxy: ${http_proxy}
    container_name: postgis
    environment:
      POSTGRES_PASSWORD: chang:M3! 
    mem_limit: 2g
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432

networks:
  default:
    external:
      name: latelier

